name: 'Lee & Zimerle'
favicon: null
layout_spectrum: 0.11454942892305553
typography_spectrum: 0.5342548610642552
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3917480951640755
  lightness: 0.19920223182998598
  saturation: 0.47160509624518454
  rhythmicContrast: 0.06399225979112089
purpose: []
